name: Print Backend TOML Config

on:
  workflow_dispatch:

jobs:
  print_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Force Print Masked Variable Space Separated
        run: echo "${{ secrets.BACKEND_TOML }}" | base64
